<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../../../style/ecceptionStyle/secondaryStyle.css">
    <link rel="stylesheet" href="../../../../style/ecceptionStyle/style.css">
    <title>try/catch block finally</title>
</head>

<body>
    <div class="body">
        <div class="header">
            <div class="box"></div>
            <div class="boxTitle"><a class="title text-center">IL BLOCCO TRY/CHATCH FINALLY</a></div>
            <div class="box">
                <a class="link" href="EcceptionIndex.html"></a>
                <figure>
                    <img src="https://www.fulci.it/wp-content/uploads/calp_Tavola-disegno-1-copia-4.jpg"
                        alt="prego ricaricare la pagina" width="70%" height="100%">
                    <figcaption>turn back</figcaption>
                </figure>
            </div>
        </div>
        <div class="box-text">
            <p class="text">
                Le eccezioni vengono catturate quando vengono invocati i metodi che sono dichiarati con la clausola
                throws, per catturarle bisogna invocare il metodo in blocchi try.Il corpo di questa istruzione viene
                eseguito fino alla fine oppure fino alla visione di una eccezione, in caso di eccezione si esaminano le
                clausole catch per vedere se esiste un gestore per quella eccezione o per una sua superclasse, se
                nessuna clausola catch cattura l'eccezione, essa viene lanciata nel metodo che l'ha provocata (che l'ha
                lanciata).Se nel try Ã¨ presente una clausola finally, il suo codice viene eseguito dopo aver completato
                tutte le altre operazioni del try, indipendentemente dal fatto che questa abbiano lanciato una eccezione
                o no.</p>
        </div>
    </div>
</body>

</html>